# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "Emulation and test"

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master", "development" ]
  schedule:
    - cron: '23 5 * * 4'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build in container
      run: ./tests/build-in-docker.sh
    - name: Export image
      run: |
        mkdir -p artifacts
        docker save pico-hsm-test:bullseye -o artifacts/docker-image.tar
    - name: Temporarily save image
      uses: actions/upload-artifact@v3
      with:
        name: docker-artifact
        path: artifacts
        retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        suite: ["pkcs11", "pytest", "sc-hsm-pkcs11"]
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Retrieve saved image
      uses: actions/download-artifact@v3
      with:
        name: docker-artifact
        path: artifacts
    - name: Load image
      run: |
        cd artifacts
        docker load -q -i docker-image.tar
    - name: Test ${{ matrix.suite }}
      run: ./tests/run-test-in-docker.sh ${{ matrix.suite }}
